version: "3"

services:
  php:
    container_name: altis-sass-php
    build:
      context: ./docker-compose/php
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./app-backend:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app

  nginx:
    container_name: altis-sass-nginx
    build:
      context: ./docker-compose/nginx
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./app-backend:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  mysql:
    container_name: altis-sass-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes:
      - setup-data:/var/lib/mysql/
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/init.sql:/etc/mysql/init.sql
    networks:
      - app
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  redis:
    container_name: altis-sass-redis
    build:
      context: ./docker-compose/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

networks:
  app:
    driver: bridge

volumes:
  setup-data:
    driver: local
